### ISSUE TITLE
Selling to traders

### ISSUE THREAD

**Issue by ghost** [Dandielo/DtlCitizensTrader#53]
Selling to traders requires your /balance to be equal or greater than the value of the items you are selling, returns a message You do not have enough money if you are selling something more valuable then your current balance

**Comment by Dandielo** [comment]
It should be fixed with the latest build.

**Comment by Adondriel** [comment]
Still doesn't seem to be fixed.
I have 5000 $ the trader has 5mil, and i try to sell an iron door for 7 to the trader. it says "Someone does not have enough money"

**Comment by Adondriel** [comment]
using: http://ci.citizensnpcs.com/job/Citizens2/782/    and    http://dev.bukkit.org/server-mods/dtltraders/files/47-dtl-traders-2-4-3-bugged/

**Comment by Dandielo** [comment]
try it with the latest dev build (save saves.yml from citizens folder first)

**Comment by Adondriel** [comment]
useing latest dev: i cannot sell an item unless i buy an item first... is there something i have to do to make him into an admin shop?

**Comment by Adondriel** [comment]
ex: Buy 1 iron door for 11, i can sell 2 iron doors for 9 each.

**Comment by Adondriel** [comment]
i found the bug
when you use /trader create (name)
the wallet type does not default to infinite, it defaults to npc

**Comment by Adondriel** [comment]
Can you give me an example of a pattern?

**Comment by Dandielo** [comment]
https://gist.github.com/Dandielo/5043595

here is an example, I'm going to finish today the wiki about the new patterns

**Comment by Dandielo** [comment]
please tell me how this bug looks like for now? It it still exists
